services:
  backend:
    build: ./backend
  frontend:
    build: ./frontend
  ml_service:
    build: ./ml_service
  pgadmin:
    environment:
      - DOMAIN_NAME=pgadmin.card-vault.develop
  redisinsight:
    environment:
      - DOMAIN_NAME=redisinsight.card-vault.develop
  proxy:
    build: ./proxy
    environment:
      - DOMAIN_NAME=card-vault.develop
    volumes:
      - ./proxy/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
