import numpy as np

class Index:
    def __init__(self, d: int) -> None: ...
    
    def add(self, x: np.ndarray) -> None: ...
    
    def search(self, x: np.ndarray, k: int) -> tuple[np.ndarray, np.ndarray]: ...
    
    @property
    def ntotal(self) -> int: ...
    
    @property
    def d(self) -> int: ...


class IndexFlatIP(Index):
    def __init__(self, d: int) -> None: ...


def normalize_L2(x: np.ndarray) -> None: ...


def write_index(index: Index, filename: str) -> None: ...


def read_index(filename: str) -> Index: ...
